- csgo/features/chams/chams.cpp
> fix chams crash

- csgo/features/visuals/visuals.cpp
> Add nullptr check inside c_visuals::draw_scope to prevent crashing.

- csgo/features/chams/chams.cpp
- csgo/features/vars.h
- csgo/features/visuals/visuals.cpp
- csgo/features/visuals/visuals.h
- csgo/menu/menu.cpp
- csgo/sdk/csgo/csgo.h
Adds a basic glow, but isn't called from the right hook. It needs to be called from DoPostScreenEffects. I'll probably fix this tomorrow.
> Add player glow.

- csgo/configs/configs.cpp
> Add glow variables to the config system.

- README.md
> Add updated and cleaner screenshots.

- csgo/hooking/hooks/CreateMove.cpp
Removes laggy feeling when create move is hooked.
> Fix Game Stutter

- csgo/features/misc/misc.cpp
- csgo/features/resolver/resolver.cpp
- csgo/features/resolver/resolver.h
- csgo/hooking/hooks/FrameStageNotify.cpp
> Add resolver base, and fixed a crash.

- csgo/features/nade_pred/nade_pred.cpp
- csgo/features/nade_pred/nade_pred.h
- csgo/hooking/hooks/CreateMove.cpp
- csgo/hooking/hooks/OverrideView.cpp
- csgo/hooking/hooks/present.cpp
- csgo/sdk/custom classes/vector.h
And made it match the menu colour.
> accurate grenade prediction.

- csgo/features/nade_pred/nade_pred.cpp
- csgo/features/nade_pred/nade_pred.h
- csgo/hooking/hooks/CreateMove.cpp
- csgo/hooking/hooks/OverrideView.cpp
- csgo/hooking/hooks/present.cpp
- csgo/sdk/custom classes/vector.h
Reverts EternityX/DEADCELL-CSGO#34
> Revert "accurate grenade prediction."

- csgo/configs/configs.cpp
- csgo/features/events/events.cpp
- csgo/features/ragebot/ragebot.cpp
- csgo/features/vars.h
- csgo/menu/menu.cpp
Title.
Note: The client sided impact (blue) isn't being drawn because weapon_fire isn't getting fired for me. Am I missing something?
> Add bullet impacts.

- csgo/features/events/events.cpp
Title.
Reference: https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/shared/sdk/sdk_player_shared.cpp#L79
> Polish up bullet impacts.

- csgo/features/misc/misc.cpp
before you could only use it with the hotkey, now the toggle button has a function.
> small improvements thirdperson, autostrafe, proptransparency

- csgo/features/animations/anim.cpp
- csgo/features/animations/anim.h
- csgo/features/ragebot/ragebot.cpp
- csgo/hooking/hooks/DoExtraBonesProcessing.cpp
- csgo/sdk/interfaces/def.h
Only check indexes we know should be linked to a player.
Also, I changed a couple more things to snake_case.
> Aimbot micro-optimization

- csgo/configs/configs.cpp
- csgo/features/autowall/autowall.cpp
- csgo/features/client.h
- csgo/features/fakelag/fakelag.cpp
- csgo/features/misc/misc.cpp
- csgo/features/misc/misc.h
- csgo/features/nade_pred/nade_pred.cpp
- csgo/features/player_log/player_log.h
- csgo/features/ragebot/ragebot.cpp
- csgo/features/vars.h
- csgo/features/visuals/visuals.cpp
- csgo/hooking/hooks/CreateMove.cpp
- csgo/hooking/hooks/FrameStageNotify.cpp
- csgo/hooking/hooks/OverrideView.cpp
- csgo/hooking/hooks/PaintTraverse.cpp
- csgo/hooking/hooks/present.cpp
- csgo/hooking/manager.h
- csgo/menu/menu.cpp
- csgo/sdk/custom classes/entity.h
- csgo/sdk/custom classes/vector.h
- csgo/sdk/interfaces/clientdll.h
- csgo/sdk/interfaces/def.h
- csgo/sdk/interfaces/i_engine_trace.h
- csgo/sdk/interfaces/i_material.h
- deadcell/math/math.cpp
- deadcell/math/math.hpp
- Flashlight
- Different options for visualizing spread and removing scope overlay
- Changed more sdk things to snake_case
- Fixed ragebot not getting random float correctly
- Dynamic tickrate check in CreateMove, instead of just 64 tick
- No scope zoom
> Lots of things, described in description

- csgo/features/misc/misc.cpp
- csgo/features/misc/misc.h
Just a temp fix until I can unasm it.
> Fix flashlight lambda issue

- csgo/sdk/custom classes/entity.h
> properly get m_hMyWeapons and m_hMyWearables

- csgo/features/anti-aim/antiaim.cpp
- csgo/features/backtrack/backtrack.cpp
- csgo/features/chams/chams.cpp
- csgo/features/ragebot/ragebot.cpp
- csgo/hooking/hooks/CreateMove.cpp
[preview](https://i.imgur.com/RFkbR5m.png)
> alpine is an n word

- csgo/features/anti-aim/antiaim.cpp
- csgo/features/backtrack/backtrack.cpp
- csgo/features/chams/chams.cpp
- csgo/features/ragebot/ragebot.cpp
- csgo/hooking/hooks/CreateMove.cpp
Reverts EternityX/DEADCELL-CSGO#82
> Revert "alpine is an n word"

- csgo/features/chaiscript/chai_wrapper.cpp
- csgo/features/chaiscript/chai_wrapper.hpp
- csgo/features/chaiscript/wrappers/chai_wrapper_entlist.hpp
- csgo/features/chaiscript/wrappers/chai_wrapper_misc.hpp
- csgo/features/chaiscript/wrappers/chai_wrapper_player.hpp
- csgo/features/chaiscript/wrappers/chai_wrapper_renderer.hpp
- csgo/hooking/hooks/EndScene.cpp
> endscene / renderer support for chaiscript

- csgo/features/anti-aim/antiaim.cpp
- csgo/features/anti-aim/antiaim.h
- csgo/features/chaiscript/chai_console.hpp
- csgo/features/chaiscript/chai_wrapper.cpp
- csgo/features/chaiscript/chai_wrapper.hpp
- csgo/hooking/hooks/CreateMove.cpp
- csgo/hooking/hooks/EndScene.cpp
- csgo/menu/menu.cpp
- csgo/menu/menu.h
put anti aims in profiles/aa/ + y or x
x aa "def create_move(cmd, vec)"
y aa "def create_move(cmd, vec, send_packet, side)"
also cool multi session support
> chaiscript multiple sessions + custom anti aim support

- csgo/menu/menu.cpp
instead of using a chaiscript function load()
it just checks in console if "load " is typed and does chai_load() on the argument
> quick fix to allow loading again

- csgo/sdk/custom classes/animstate.h
Game now uses client.dll instead.
> Fix last client_panorama.dll reference
